# Generated by Django 3.2 on 2021-05-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiumaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='grado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
