# Generated by Django 3.2 on 2021-05-12 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikiumaApp', '0002_auto_20210509_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValoracionAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=500)),
                ('comentario', models.TextField(max_length=500)),
                ('puntuacion', models.IntegerField()),
                ('reportado', models.BooleanField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikiumaApp.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='ValoracionProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=500)),
                ('comentario', models.TextField(max_length=500)),
                ('puntuacion', models.IntegerField()),
                ('reportado', models.BooleanField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikiumaApp.profesor')),
            ],
        ),
        migrations.DeleteModel(
            name='Valoraciones',
        ),
    ]
