# Generated by Django 3.2 on 2021-05-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiumaApp', '0003_auto_20210512_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
        migrations.AlterModelOptions(
            name='profesorasignatura',
            options={'verbose_name': 'Profesor-Asignatura', 'verbose_name_plural': 'Profesores-Asignaturas'},
        ),
        migrations.AlterModelOptions(
            name='valoracionasignatura',
            options={'verbose_name': 'Valoración-Asignatura', 'verbose_name_plural': 'Valoraciones-Asignaturas'},
        ),
        migrations.AlterModelOptions(
            name='valoracionprofesor',
            options={'verbose_name': 'Valoración-Profesor', 'verbose_name_plural': 'Valoraciones-Profesores'},
        ),
        migrations.AddField(
            model_name='asignatura',
            name='grado',
            field=models.ManyToManyField(to='wikiumaApp.Grado', verbose_name='Grados en los que se imparte'),
        ),
    ]
